name: Update wex.json

on:
  push:
    branches:
      - main
  watch:
  workflow_dispatch:
    # 允许手动触发
  schedule:
    - cron: '0 20 * * *'  # 每天20:00（UTC时间）执行

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v2

    - name: Fetch new wex.json
      run: |
        cd ${{ github.workspace }}
        file="wex.json"
        curl -s www.xn--sss604efuw.com/jm/jiemi.php?url=http%3A%2F%2Ftvbox.%E7%8E%8B%E4%BA%8C%E5%B0%8F%E6%94%BE%E7%89%9B%E5%A8%83.top >$file

    - name: Upload to KStore
      env:
        KSTORE_FOLDER_ID: ${{ secrets.KSTORE_FOLDER_ID }}  # 使用 GitHub Secrets 存储
        KSTORE_ACCESS_TOKEN: ${{ secrets.KSTORE_ACCESS_TOKEN }}
      run: |
        curl -F "file=@wex.json" "https://upload.kstore.space/upload/$KSTORE_FOLDER_ID?access_token=$KSTORE_ACCESS_TOKEN"

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add wex.json
        git commit -m "Update wex.json"
        git push origin HEAD:main
