name: Update wex.json

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch new wex.json
      run: |
        cd ${{ github.workspace }}
        curl -s http://6080.eu.org/?url=http://tvbox.xn--4kq62z5rby2qupq9ub.top > wex.json

    - name: Commit and push changes
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add wex.json
        git commit -m "Update wex.json"
        git push origin HEAD:main